[project]
name = "test-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "netcdf4>=1.7.2",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "rasterio>=1.4.3",
    "scipy>=1.15.2",
]
